### ISSUE TITLE
JabRef does not open files linked to entries

### ISSUE THREAD

**Issue by i5qme2b944w3** [flathub/org.jabref.jabref#3]
Telling JabRef to open a file (pdf, djvu, etc.) linked to an entry gives no response.

Expected response is an "Open with..." dialog, presumably using the xdg-desktop-portal service for Flatpak, so that the user can select an application outside of JabRef's sandbox to open the file.

Additional info:

- I'm using Debian 11, with KDE Plasma 5.17.5 desktop environment.

- I've tried using both relative and absolute file paths in entries, and neither work.

- JabRef installed from Snap instead of Flatpak successfully uses the expected "Open with..." dialog. So does Zotero installed from Flatpak. So as far as I can tell, the problem isn't with my xdg-desktop-portal setup, but I could be wrong.

- Telling JabRef to open URLs or DOIs succeeds: they are opened directly in my web browser, with no "Open with..." dialog first.

**Comment by LyzardKing** [comment]
@i5qme2b944w3 
Is it the flatpak that has this issue? Does the snap package work properly?

**Comment by i5qme2b944w3** [comment]
It's the flatpak that has this issue; the snap package works properly. Sorry for the ambiguity.

**Comment by LyzardKing** [comment]
Not a problem! Thanks for opening the issue!
I mainly use the snap package, but I'll have a look at the flatpak.
If you find more issues between the two please let us know!

**Comment by LyzardKing** [comment]
@bilelmoussaoui 
Sorry to ping you for this one, but do you have any idea on what is needed?
The files are in a subdirectory of /home/<user>/, so I was under the impression that `filesystem=home` would be enough.
Is a different runtime needed (i.e. the gnome one) to enable the xdg desktop integrations?

**Comment by i5qme2b944w3** [comment]
Just to check: was this the right place to open this issue? Or should I have opened it at the [main JabRef repository](https://github.com/JabRef/jabref)?
I ask because I've spotted another issue with the flatpak package, and want to open it in the right place.

**Comment by LyzardKing** [comment]
This is the correct repo for flatpak-only issues.

**Comment by bilelmoussaoui** [comment]
> @bilelmoussaoui
> Sorry to ping you for this one, but do you have any idea on what is needed?
> The files are in a subdirectory of /home//, so I was under the impression that `filesystem=home` would be enough.
> Is a different runtime needed (i.e. the gnome one) to enable the xdg desktop integrations?

How are you opening the file?

**Comment by LyzardKing** [comment]
This will be solved with the linked PR.
In flatpak we cannot use xdg-open, but the java awt desktop integration still works.

**Comment by i5qme2b944w3** [comment]
Thanks, the issue is resolved now.
