### ISSUE TITLE
Flatpak'ed JabRef doesn't recognise journal abbreviation forms without periods

### ISSUE THREAD

**Issue by i5qme2b944w3** [flathub/org.jabref.jabref#6]
In the un/abbreviate journal names function (either via the button positioned next to Journal/Journaltitle/Journalsubtitle/... fields in the Entry Editor, or in the Quality menu), there is a curious issue with the flatpak version of JabRef.

Roughly, JabRef seems to use three levels of abbreviation for most journal names: unabbreviated, abbreviated with periods to mark abbreviated words, and abbreviated without the periods. For example, the various forms of the journal title "Physical Review D" are: `Physical Review D`, `Phys. Rev. D`, and `Phys Rev D`.

However, the flatpak version of JabRef fails to unabbreviate from the "abbreviated without periods" form.

For instance, when clicking the un/abbreviate button in the Entry Editor, JabRef would normally cycle through `Physical Review D` -> `Phys. Rev. D` -> `Phys Rev D` -> `Physical Review D` -> etc. (The snap package behaves this way.) But in the flatpak version, the cycle gets stuck at `Phys Rev D`, at which point pressing the button does nothing. Similarly, the `Quality -> Unabbreviate journal names` menu button will also fail to switch from `Phys Rev D` back to `Physical Review D`.

So it seems that the flatpak version of JabRef fails to recognize that `Phys Rev D` is a valid abbreviation of `Physical Review D`, whereas the snap version does recognize it.

(I have checked this behaviour with journal names other than `Physical Review D` as well; it seems to occur for any journal names on the built-in abbreviation list.)

**Comment by LyzardKing** [comment]
Thanks for the issue report,
did you test it in the deb/snap?

**Comment by i5qme2b944w3** [comment]
I've tested in the snap, which successfully unabbreviates these journal names. This suggests to me that the problem is just with the flatpak, but I haven't tested the deb.

**Comment by LyzardKing** [comment]
Do you see any error in the commandline if you run `flatpak run org.jabref.jabref`?

**Comment by i5qme2b944w3** [comment]
I get the following error messages as JabRef is starting:
```
$ flatpak run org.jabref.jabref
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [d]
ERROR StatusLogger Unrecognized conversion specifier [d] starting at position 16 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [thread]
ERROR StatusLogger Unrecognized conversion specifier [thread] starting at position 25 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [level]
ERROR StatusLogger Unrecognized conversion specifier [level] starting at position 35 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [logger]
ERROR StatusLogger Unrecognized conversion specifier [logger] starting at position 47 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [msg]
ERROR StatusLogger Unrecognized conversion specifier [msg] starting at position 54 in conversion pattern.
ERROR StatusLogger Unrecognized format specifier [n]
ERROR StatusLogger Unrecognized conversion specifier [n] starting at position 56 in conversion pattern.

(java:4): Gdk-WARNING **: 13:42:04.528: XSetErrorHandler() called with a GDK error trap pushed. Don't do that.
```

**Comment by LyzardKing** [comment]
What about when you try to run the unabbreviation function?

**Comment by i5qme2b944w3** [comment]
I get no errors or warnings when I use the abbreviate or unabbreviate functions.

**Comment by i5qme2b944w3** [comment]
Issue fixed in recent update

**Comment by LyzardKing** [comment]
Good to know. It's useful to note that the flatpak mirrors only the stable release, while the snap has the beta/edge channels that wil show new features/fixes.
